---
title: "AYU - Week 1"
format: 
  html:
    toc: true
editor: visual
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

------------------------------------------------------------------------

**Instruction**: *Scan your answer into pdf/word document then submit to Canvas.*
---

## Question 1

Given the following four time series, y1, y2, y3 and y4. Which of the time following time series

- has/have trend only

- has/have seasonality only

- has/have both trend and seasonality

- has/have no trend and no seasonality

```{r}
y1 = ts(1 + rnorm(100, sd = 1))
y2 = ts(c(1:100)+rnorm(100, sd = 1))
y3 = ts(10*cos(.3*c(1:100))+rnorm(100, sd = 1))
y4 = ts(c(1:100)+ 7*cos(c(1:100))+rnorm(100, sd = 1))

plot(y1)
plot(y2)
plot(y3)
plot(y4)
```


## Question 2

Given the following time series.

| t   | $y_t$ |
|:----|:------|
| 1   | 1     |
| 2   | 3     |
| 3   | 5     |
| 4   | 8     |
| 5   | 12    |
| 6   | 13    |
| 7   | 16    |

a. Calculate the auto-correlation at lag 1.

b. Calculate the auto-correlation at lag 2.

c. Calculate the auto-correlation at lag 3.

```{r, eval=FALSE}
y = c(1,3,5,8,12,13,16)
a = acf(y)
a$acf
```


## Question 3

Which of the following series is not stationary. Explain the reason. 

```{r}
y1 = ts(1 + rnorm(100, sd = 1))
y2 = ts(c(1:100)+rnorm(100, sd = 1))
y3 = ts(c(1:100)+10*cos(.3*c(1:100))+rnorm(100, sd = 1))
y4 = ts(c(rnorm(50), rnorm(50, sd =10)))

plot(y1)
plot(y2)
plot(y3)
plot(y4)
```


## Question 4

The ACF of several time series are given below.  Based on the ACF, which time series is/are stationary and why?

```{r}
set.seed(2024)
y1 = ts(1 + rnorm(100, sd = 1))
y2 = ts(c(1:100)+rnorm(100, sd = 1))
y3 = ts(-c(1:100)+10*cos(.3*c(1:100))+rnorm(100, sd = 1))
y4 = arima.sim(list(order=c(1,0,0), ar=c(.6)), n=100)
y5 = ts(5*cos(c(1:100))+ rnorm(100))
  
acf(y1)
acf(y2)
acf(y3)
acf(y4)
acf(y5)
```

------------------------------------------------------------------------